[package]
name = "inf1-svc-inf-core"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
inf1-ctl-core = { workspace = true }
inf1-svc-core = { workspace = true }
sanctum-u64-ratio = { workspace = true }
